spacing cleanup

diff --git a/lib/npm b/lib/npm
--- a/lib/npm
+++ b/lib/npm
@@ -2,22 +2,22 @@
 
 run_npm() {
 
-    # Check for npm
-    if type_exists 'npm'; then
-        e_header "Installing Node.js packages..."
+  # Check for npm
+  if type_exists 'npm'; then
+    e_header "Installing Node.js packages..."
 
-        # List of npm packages
-        local packages="bower gify grunt-cli jshint karma yo"
+    # List of npm packages
+    local packages="bower gify grunt-cli jshint karma yo"
 
-        # Install packages globally and quietly
-        npm install $packages --global --quiet
+    # Install packages globally and quietly
+    npm install $packages --global --quiet
 
-        [[ $? ]] && e_success "Done"
-    else
-        printf "\n"
-        e_error "Error: npm not found."
-        printf "Aborting...\n"
-        exit
-    fi
+    [[ $? ]] && e_success "Done"
+  else
+    printf "\n"
+    e_error "Error: npm not found."
+    printf "Aborting...\n"
+    exit
+  fi
 
 }
