node: refactor setup process, add gulp, remove gify

diff --git a/lib/npm b/lib/npm
--- a/lib/npm
+++ b/lib/npm
@@ -1,12 +1,42 @@
 #!/bin/bash
 
+install_ndenv() {
+  if ! type_exists 'ndenv'; then
+    e_header "Installing ndenv..."
+    git clone https://github.com/riywo/ndenv ~/.ndenv 1> /dev/null 2> /dev/null
+    git clone https://github.com/riywo/node-build.git ~/.ndenv/plugins/node-build 1> /dev/null 2> /dev/null
+  fi
+
+  # temporarily add ndenv to PATH to make it easier to install node
+  export PATH="${PATH}:${HOME}/.ndenv/bin"
+
+  # initialize ndenv in current session to expose node & npm to PATH as well
+  eval "$(ndenv init -)"
+}
+
+install_node() {
+  if ! type_exists 'ndenv'; then
+    printf "\n"
+    e_error "Error: use ndenv to install node. ndenv is not installed"
+    printf "Aborting...\n"
+    exit
+  fi
+
+  # install latest version
+  local latest_node_version=$(ndenv install --list | sed 's/^ *//;s/ *$//' | grep "^v" | tail -n1)
+  [ ! -d "$HOME/.ndenv/versions/${latest_node_version}" ] && ndenv install $latest_node_version
+
+  # set node to use latest version in current shell session
+  ndenv shell $latest_node_version
+}
+
 run_npm() {
   # Check for npm
   if type_exists 'npm'; then
     e_header "Installing Node.js packages..."
 
     # List of npm packages
-    local packages="bower gify grunt-cli jshint karma yo uglify-js"
+    local packages="bower gulp grunt-cli jshint karma yo uglify-js"
 
     # Install packages globally and quietly
     npm install $packages --global --quiet
